# .github/workflows/jekyll-gh-pages.yml

name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------------------------------------------
      # 这是你缺失的关键步骤
      # -----------------------------------------------------------------
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # 确保你的项目根目录有一个 .ruby-version 文件
          # 内容为 3.3.0
          ruby-version: '3.3.0'

          # 这一行会自动运行 bundle install
          # 并安装你 Gemfile 中的 minimal-mistakes-jekyll
          bundler-cache: true
      # -----------------------------------------------------------------

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        # 这里我们使用 bundle exec 来确保它使用了正确的 gem
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4